# Generated by Django 3.2 on 2022-02-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='transaction_history',
            new_name='user',
        ),
    ]
