# Generated by Django 3.2 on 2022-02-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='symbol',
            field=models.CharField(default='+', max_length=1),
        ),
    ]
